// Physics Logic Data from product.md
const physicsData = {
    'tanjore-doll': {
        title: 'Tanjore Doll - Physics & Kinematics',
        content: `
            <h4>Design Philosophy</h4>
            <p>The "Tanjore Doll" is a marvel of center-of-gravity engineering.</p>
            
            <h4>Center of Mass</h4>
            <ul>
                <li>The base is heavily weighted with <strong>terracotta/clay</strong></li>
                <li>Places the center of mass <strong>extremely low</strong></li>
            </ul>
            
            <h4>Restoring Force</h4>
            <ul>
                <li>When pushed, the torque generated by the low center of mass creates a <strong>restoring force</strong></li>
                <li>This brings the doll back to <strong>vertical equilibrium</strong></li>
                <li>The physics principle ensures the doll never falls over</li>
            </ul>
        `
    },
    
    'big-temple': {
        title: 'Brihadeeswarar Temple - Architectural Logic',
        content: `
            <h4>Vimana Engineering</h4>
            <ul>
                <li>Main tower height: <strong>216 feet (66 meters)</strong></li>
                <li>Architectural precision spanning over 1000 years</li>
            </ul>
            
            <h4>The Monolith Cap</h4>
            <ul>
                <li>The Kumbam at the top weighs approximately <strong>80 tons</strong></li>
                <li>Single piece of granite carved and placed without modern machinery</li>
            </ul>
            
            <h4>Shadow Mystery</h4>
            <ul>
                <li>Legend: Shadow never falls on the ground at noon</li>
                <li>Reality: Base is so wide that shadow falls <strong>within the structure's perimeter</strong></li>
            </ul>
            
            <h4>Interlocking Stone System</h4>
            <ul>
                <li>Uses <strong>no mortar</strong> - held together by gravity</li>
                <li>Employs a "puzzle-lock" system of <strong>precisely cut granite</strong></li>
            </ul>
        `
    },
    
    'tanjore-painting': {
        title: 'Tanjore Painting - Gold Leaf Technology',
        content: `
            <h4>Material Excellence</h4>
            <ul>
                <li><strong>22-carat gold foil</strong> used for the "Teck" work</li>
                <li>Creates the distinctive golden luminescence</li>
            </ul>
            
            <h4>Relief Technique</h4>
            <ul>
                <li>3D effect created using <strong>"Sukkann Karuppu"</strong></li>
                <li>Mixture of unslaked lime and glue</li>
                <li>Builds raised surfaces before gold application</li>
            </ul>
            
            <h4>Artistic Process</h4>
            <ul>
                <li>Base canvas preparation with chalk and tamarind seed paste</li>
                <li>Detailed sketching and relief work</li>
                <li>Final gold foil application and burnishing</li>
            </ul>
        `
    },
    
    'art-plates': {
        title: 'Tri-Metal Art Plates - Metallurgy Mastery',
        content: `
            <h4>Composition Science</h4>
            <ul>
                <li>Base material: <strong>Brass</strong> (copper-zinc alloy)</li>
                <li>Overlays: <strong>Silver and copper</strong> detailing</li>
                <li>Creates depth and contrast through metal properties</li>
            </ul>
            
            <h4>Traditional Motifs</h4>
            <ul>
                <li><strong>Ashtalakshmi</strong> - Eight forms of Goddess Lakshmi</li>
                <li><strong>Dashavatara</strong> - Ten avatars of Lord Vishnu</li>
                <li>Intricate geometric and floral patterns</li>
            </ul>
            
            <h4>Crafting Technique</h4>
            <ul>
                <li>Repoussé work - hammering from reverse side</li>
                <li>Chasing - detailed front-side engraving</li>
                <li>Patination for antique finish</li>
            </ul>
        `
    },
    
    'degree-coffee': {
        title: 'Degree Coffee - Lactometer Precision',
        content: `
            <h4>The "Degree" Logic</h4>
            <ul>
                <li>Refers to the <strong>specific gravity of milk</strong></li>
                <li>Milk checked with "Degree meter" (lactometer)</li>
                <li>Required density: <strong>1.030+</strong> for pure, thick milk</li>
            </ul>
            
            <h4>Scientific Brewing</h4>
            <ul>
                <li>Milk density affects coffee extraction and taste</li>
                <li>Higher density = richer, creamier texture</li>
                <li>Traditional quality control method</li>
            </ul>
            
            <h4>Cultural Significance</h4>
            <ul>
                <li>Symbol of hospitality and precision</li>
                <li>Each household maintains specific standards</li>
                <li>Passed down through generations</li>
            </ul>
        `
    },
    
    'ashoka-halwa': {
        title: 'Ashoka Halwa - Moong Dal Translucence Science',
        content: `
            <h4>Viscosity Engineering</h4>
            <ul>
                <li>Should have a <strong>"slippery" texture</strong></li>
                <li>Achieved by slow-cooking moong dal with <strong>equal parts ghee</strong></li>
                <li>Temperature control creates perfect consistency</li>
            </ul>
            
            <h4>Origin & Heritage</h4>
            <ul>
                <li>Specifically associated with <strong>Thiruvaiyaru</strong></li>
                <li>Home of Saint Tyagaraja, the musical legend</li>
                <li>Traditional preparation during music festivals</li>
            </ul>
            
            <h4>Scientific Process</h4>
            <ul>
                <li>Moong dal proteins break down during slow cooking</li>
                <li>Ghee emulsification creates smooth texture</li>
                <li>Sugar crystallization controlled for perfect sweetness</li>
            </ul>
        `
    }
};

// DOM Elements
const cards = document.querySelectorAll('.card');
const popup = document.getElementById('physics-popup');
const popupTitle = document.querySelector('.popup-title');
const popupBody = document.querySelector('.popup-body');

// Event Listeners
document.addEventListener('DOMContentLoaded', function() {
    // Add hover effects and click handlers to cards
    cards.forEach(card => {
        const physicsKey = card.getAttribute('data-physics');
        
        // Click to show popup
        card.addEventListener('click', function() {
            showPhysicsPopup(physicsKey);
        });
        
        // Enhanced hover effects
        card.addEventListener('mouseenter', function() {
            this.style.transform = 'translateY(-8px) scale(1.02)';
        });
        
        card.addEventListener('mouseleave', function() {
            this.style.transform = 'translateY(0) scale(1)';
        });
    });
    
    // Close popup when clicking outside
    popup.addEventListener('click', function(e) {
        if (e.target === popup) {
            closePhysicsPopup();
        }
    });
    
    // Close popup with Escape key
    document.addEventListener('keydown', function(e) {
        if (e.key === 'Escape' && popup.classList.contains('active')) {
            closePhysicsPopup();
        }
    });
    
    // Add smooth scrolling for better UX
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function (e) {
            e.preventDefault();
            const target = document.querySelector(this.getAttribute('href'));
            if (target) {
                target.scrollIntoView({
                    behavior: 'smooth',
                    block: 'start'
                });
            }
        });
    });
});

// Show Physics Logic Popup
function showPhysicsPopup(physicsKey) {
    const data = physicsData[physicsKey];
    if (data) {
        popupTitle.textContent = data.title;
        popupBody.innerHTML = data.content;
        popup.classList.add('active');
        document.body.style.overflow = 'hidden'; // Prevent background scrolling
    }
}

// Close Physics Logic Popup
function closePhysicsPopup() {
    popup.classList.remove('active');
    document.body.style.overflow = 'auto'; // Restore scrolling
}

// Add some interactive animations
function addInteractiveEffects() {
    // Parallax effect for background
    window.addEventListener('scroll', function() {
        const scrolled = window.pageYOffset;
        const parallax = document.body;
        const speed = scrolled * 0.5;
        parallax.style.backgroundPosition = `center ${speed}px`;
    });
    
    // Stagger animation for cards on load
    const observer = new IntersectionObserver((entries) => {
        entries.forEach((entry, index) => {
            if (entry.isIntersecting) {
                setTimeout(() => {
                    entry.target.style.opacity = '1';
                    entry.target.style.transform = 'translateY(0)';
                }, index * 100);
            }
        });
    });
    
    cards.forEach(card => {
        card.style.opacity = '0';
        card.style.transform = 'translateY(20px)';
        card.style.transition = 'opacity 0.6s ease, transform 0.6s ease';
        observer.observe(card);
    });
}

// Initialize interactive effects
addInteractiveEffects();

// Add a subtle typing effect to the title
function typeWriter(element, text, speed = 100) {
    let i = 0;
    element.textContent = '';
    
    function type() {
        if (i < text.length) {
            element.textContent += text.charAt(i);
            i++;
            setTimeout(type, speed);
        }
    }
    
    type();
}

// Optional: Uncomment to add typing effect to title
// window.addEventListener('load', function() {
//     const title = document.querySelector('.title');
//     const originalText = title.textContent;
//     typeWriter(title, originalText, 150);
// });